/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;


import Simulacion.Jugada;
import java.awt.Color;

/**
 *
 * @author Mairim
 */
public class  Equipos extends javax.swing.JFrame {
Jugada Jugada;
    /**
     * Creates new form Equipos
     */
    public Equipos() {
        initComponents();
        setTitle("Jugadores");
        setResizable(false);
        setLocationRelativeTo(this);
        jTextArea2.setBackground(new Color(0,0,0,0));
                        jScrollPane1.setBackground(new Color(0,0,0,0));
                        jScrollPane1.getViewport().setOpaque(false);
                        jScrollPane1.setOpaque(false);
               
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEquipo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelEquipo2 = new javax.swing.JLabel();
        jLabelEquipo3 = new javax.swing.JLabel();
        jLabelEquipo4 = new javax.swing.JLabel();
        jLabelEquipo5 = new javax.swing.JLabel();
        jLabelEquipo6 = new javax.swing.JLabel();
        jLabelEquipo7 = new javax.swing.JLabel();
        jLabelEquipo8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelEquipo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEquipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rojo.png"))); // NOI18N
        jLabelEquipo1.setText("1");
        jLabelEquipo1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Equipos Participantes:");

        jLabelEquipo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEquipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro.png"))); // NOI18N
        jLabelEquipo2.setText("2");

        jLabelEquipo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEquipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/azul.png"))); // NOI18N
        jLabelEquipo3.setText("3");

        jLabelEquipo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEquipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/verde.png"))); // NOI18N
        jLabelEquipo4.setText("4");

        jLabelEquipo5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEquipo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/morado.png"))); // NOI18N
        jLabelEquipo5.setText("5");

        jLabelEquipo6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEquipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rosado.png"))); // NOI18N
        jLabelEquipo6.setText("6");

        jLabelEquipo7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEquipo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/marron.png"))); // NOI18N
        jLabelEquipo7.setText("7");

        jLabelEquipo8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEquipo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gris.png"))); // NOI18N
        jLabelEquipo8.setText("8");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelEquipo6)
                        .addComponent(jLabelEquipo7)
                        .addComponent(jLabelEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelEquipo4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEquipo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEquipo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabelEquipo5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabelEquipo8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabelEquipo1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelEquipo2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEquipo3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEquipo4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEquipo5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEquipo6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEquipo7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEquipo8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabelEquipo1;
    public static javax.swing.JLabel jLabelEquipo2;
    public static javax.swing.JLabel jLabelEquipo3;
    public static javax.swing.JLabel jLabelEquipo4;
    public static javax.swing.JLabel jLabelEquipo5;
    public static javax.swing.JLabel jLabelEquipo6;
    public static javax.swing.JLabel jLabelEquipo7;
    public static javax.swing.JLabel jLabelEquipo8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
