/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.awt.Color;

/**
 *
 * @author cat clt
 */
public class VCliente extends javax.swing.JFrame {
private String ip;
    /**
     * Creates new form VCliente
     */
    public static ConectorCliente servidor,cliente;
    //Animal conejo;
    
    public VCliente() {
        
        initComponents();
        setSize(400,620);
        setTitle("Pista de Carreras");
        setLocationRelativeTo(null);
        jTextArea1.setOpaque(false);
                        jTextArea1.setBackground(new Color(0,0,0,0));
                        jScrollPane1.setBackground(new Color(0,0,0,0));
                        jScrollPane1.getViewport().setOpaque(false);
                        jScrollPane1.setOpaque(false);
                        jScrollPane1.setVisible(false);
                    jTextArea1.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel3.setVisible(false);
  
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCorredor4Equipo1 = new javax.swing.JLabel();
        jLabelCorredor3Equipo1 = new javax.swing.JLabel();
        jLabelCorredor2Equipo1 = new javax.swing.JLabel();
        jLabelCorredor1Equipo1 = new javax.swing.JLabel();
        jLabelCorredor4Equipo8 = new javax.swing.JLabel();
        jLabelCorredor3Equipo8 = new javax.swing.JLabel();
        jLabelCorredor2Equipo8 = new javax.swing.JLabel();
        jLabelCorredor1Equipo8 = new javax.swing.JLabel();
        jLabelCorredor4Equipo7 = new javax.swing.JLabel();
        jLabelCorredor3Equipo7 = new javax.swing.JLabel();
        jLabelCorredor2Equipo7 = new javax.swing.JLabel();
        jLabelCorredor1Equipo7 = new javax.swing.JLabel();
        jLabelCorredor4Equipo6 = new javax.swing.JLabel();
        jLabelCorredor3Equipo6 = new javax.swing.JLabel();
        jLabelCorredor2Equipo6 = new javax.swing.JLabel();
        jLabelCorredor1Equipo6 = new javax.swing.JLabel();
        jLabelCorredor4Equipo5 = new javax.swing.JLabel();
        jLabelCorredor3Equipo5 = new javax.swing.JLabel();
        jLabelCorredor2Equipo5 = new javax.swing.JLabel();
        jLabelCorredor1Equipo5 = new javax.swing.JLabel();
        jLabelCorredor4Equipo4 = new javax.swing.JLabel();
        jLabelCorredor3Equipo4 = new javax.swing.JLabel();
        jLabelCorredor2Equipo4 = new javax.swing.JLabel();
        jLabelCorredor1Equipo4 = new javax.swing.JLabel();
        jLabelCorredor1Equipo2 = new javax.swing.JLabel();
        jLabelCorredor2Equipo2 = new javax.swing.JLabel();
        jLabelCorredor3Equipo2 = new javax.swing.JLabel();
        jLabelCorredor4Equipo2 = new javax.swing.JLabel();
        jLabelCorredor4Equipo3 = new javax.swing.JLabel();
        jLabelCorredor3Equipo3 = new javax.swing.JLabel();
        jLabelCorredor2Equipo3 = new javax.swing.JLabel();
        jLabelCorredor1Equipo3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabelPista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabelCorredor4Equipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rojo.png"))); // NOI18N
        getContentPane().add(jLabelCorredor4Equipo1);
        jLabelCorredor4Equipo1.setBounds(260, 370, 20, 20);

        jLabelCorredor3Equipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rojo.png"))); // NOI18N
        getContentPane().add(jLabelCorredor3Equipo1);
        jLabelCorredor3Equipo1.setBounds(370, 140, 20, 19);

        jLabelCorredor2Equipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rojo.png"))); // NOI18N
        getContentPane().add(jLabelCorredor2Equipo1);
        jLabelCorredor2Equipo1.setBounds(110, 200, 20, 19);

        jLabelCorredor1Equipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rojo.png"))); // NOI18N
        getContentPane().add(jLabelCorredor1Equipo1);
        jLabelCorredor1Equipo1.setBounds(0, 430, 20, 19);

        jLabelCorredor4Equipo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gris.png"))); // NOI18N
        getContentPane().add(jLabelCorredor4Equipo8);
        jLabelCorredor4Equipo8.setBounds(310, 550, 20, 20);

        jLabelCorredor3Equipo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gris.png"))); // NOI18N
        getContentPane().add(jLabelCorredor3Equipo8);
        jLabelCorredor3Equipo8.setBounds(180, 90, 20, 19);

        jLabelCorredor2Equipo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gris.png"))); // NOI18N
        getContentPane().add(jLabelCorredor2Equipo8);
        jLabelCorredor2Equipo8.setBounds(0, 10, 20, 19);

        jLabelCorredor1Equipo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gris.png"))); // NOI18N
        getContentPane().add(jLabelCorredor1Equipo8);
        jLabelCorredor1Equipo8.setBounds(200, 470, 20, 19);

        jLabelCorredor4Equipo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/marron.png"))); // NOI18N
        getContentPane().add(jLabelCorredor4Equipo7);
        jLabelCorredor4Equipo7.setBounds(290, 520, 20, 20);

        jLabelCorredor3Equipo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/marron.png"))); // NOI18N
        getContentPane().add(jLabelCorredor3Equipo7);
        jLabelCorredor3Equipo7.setBounds(210, 90, 20, 19);

        jLabelCorredor2Equipo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/marron.png"))); // NOI18N
        getContentPane().add(jLabelCorredor2Equipo7);
        jLabelCorredor2Equipo7.setBounds(30, 30, 20, 19);

        jLabelCorredor1Equipo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/marron.png"))); // NOI18N
        getContentPane().add(jLabelCorredor1Equipo7);
        jLabelCorredor1Equipo7.setBounds(160, 480, 20, 19);

        jLabelCorredor4Equipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rosado.png"))); // NOI18N
        getContentPane().add(jLabelCorredor4Equipo6);
        jLabelCorredor4Equipo6.setBounds(270, 500, 20, 20);

        jLabelCorredor3Equipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rosado.png"))); // NOI18N
        getContentPane().add(jLabelCorredor3Equipo6);
        jLabelCorredor3Equipo6.setBounds(240, 90, 20, 20);

        jLabelCorredor2Equipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rosado.png"))); // NOI18N
        getContentPane().add(jLabelCorredor2Equipo6);
        jLabelCorredor2Equipo6.setBounds(60, 60, 20, 20);

        jLabelCorredor1Equipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rosado.png"))); // NOI18N
        getContentPane().add(jLabelCorredor1Equipo6);
        jLabelCorredor1Equipo6.setBounds(130, 480, 20, 20);

        jLabelCorredor4Equipo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/morado.png"))); // NOI18N
        getContentPane().add(jLabelCorredor4Equipo5);
        jLabelCorredor4Equipo5.setBounds(260, 470, 20, 20);

        jLabelCorredor3Equipo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/morado.png"))); // NOI18N
        getContentPane().add(jLabelCorredor3Equipo5);
        jLabelCorredor3Equipo5.setBounds(270, 90, 20, 20);

        jLabelCorredor2Equipo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/morado.png"))); // NOI18N
        getContentPane().add(jLabelCorredor2Equipo5);
        jLabelCorredor2Equipo5.setBounds(80, 80, 20, 20);

        jLabelCorredor1Equipo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/morado.png"))); // NOI18N
        getContentPane().add(jLabelCorredor1Equipo5);
        jLabelCorredor1Equipo5.setBounds(110, 470, 20, 20);

        jLabelCorredor4Equipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/verde.png"))); // NOI18N
        getContentPane().add(jLabelCorredor4Equipo4);
        jLabelCorredor4Equipo4.setBounds(250, 440, 19, 20);

        jLabelCorredor3Equipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/verde.png"))); // NOI18N
        getContentPane().add(jLabelCorredor3Equipo4);
        jLabelCorredor3Equipo4.setBounds(300, 100, 19, 20);

        jLabelCorredor2Equipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/verde.png"))); // NOI18N
        getContentPane().add(jLabelCorredor2Equipo4);
        jLabelCorredor2Equipo4.setBounds(100, 110, 19, 20);

        jLabelCorredor1Equipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/verde.png"))); // NOI18N
        getContentPane().add(jLabelCorredor1Equipo4);
        jLabelCorredor1Equipo4.setBounds(80, 465, 19, 20);

        jLabelCorredor1Equipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro.png"))); // NOI18N
        getContentPane().add(jLabelCorredor1Equipo2);
        jLabelCorredor1Equipo2.setBounds(30, 440, 20, 20);

        jLabelCorredor2Equipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro.png"))); // NOI18N
        getContentPane().add(jLabelCorredor2Equipo2);
        jLabelCorredor2Equipo2.setBounds(110, 170, 20, 20);

        jLabelCorredor3Equipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro.png"))); // NOI18N
        getContentPane().add(jLabelCorredor3Equipo2);
        jLabelCorredor3Equipo2.setBounds(350, 120, 20, 20);

        jLabelCorredor4Equipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/negro.png"))); // NOI18N
        getContentPane().add(jLabelCorredor4Equipo2);
        jLabelCorredor4Equipo2.setBounds(250, 390, 20, 20);

        jLabelCorredor4Equipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/azul.png"))); // NOI18N
        jLabelCorredor4Equipo3.setText("jLabel1");
        getContentPane().add(jLabelCorredor4Equipo3);
        jLabelCorredor4Equipo3.setBounds(250, 410, 20, 30);

        jLabelCorredor3Equipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/azul.png"))); // NOI18N
        jLabelCorredor3Equipo3.setText("jLabel1");
        getContentPane().add(jLabelCorredor3Equipo3);
        jLabelCorredor3Equipo3.setBounds(330, 110, 20, 20);

        jLabelCorredor2Equipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/azul.png"))); // NOI18N
        jLabelCorredor2Equipo3.setText("jLabel1");
        getContentPane().add(jLabelCorredor2Equipo3);
        jLabelCorredor2Equipo3.setBounds(110, 140, 20, 20);

        jLabelCorredor1Equipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/azul.png"))); // NOI18N
        jLabelCorredor1Equipo3.setText("jLabel1");
        getContentPane().add(jLabelCorredor1Equipo3);
        jLabelCorredor1Equipo3.setBounds(50, 460, 20, 20);

        jLabel2.setFont(new java.awt.Font("Castellar", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fin de la Carrera");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 140, 300, 50);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(8);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextArea1.setCaretColor(new java.awt.Color(255, 0, 0));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setEnabled(false);
        jTextArea1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 350, 220);

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Resultados:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 170, 170, 50);

        jLabelPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/central.png"))); // NOI18N
        getContentPane().add(jLabelPista);
        jLabelPista.setBounds(0, 0, 400, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabelCorredor1Equipo1;
    public static javax.swing.JLabel jLabelCorredor1Equipo2;
    public static javax.swing.JLabel jLabelCorredor1Equipo3;
    public static javax.swing.JLabel jLabelCorredor1Equipo4;
    public static javax.swing.JLabel jLabelCorredor1Equipo5;
    public static javax.swing.JLabel jLabelCorredor1Equipo6;
    public static javax.swing.JLabel jLabelCorredor1Equipo7;
    public static javax.swing.JLabel jLabelCorredor1Equipo8;
    public static javax.swing.JLabel jLabelCorredor2Equipo1;
    public static javax.swing.JLabel jLabelCorredor2Equipo2;
    public static javax.swing.JLabel jLabelCorredor2Equipo3;
    public static javax.swing.JLabel jLabelCorredor2Equipo4;
    public static javax.swing.JLabel jLabelCorredor2Equipo5;
    public static javax.swing.JLabel jLabelCorredor2Equipo6;
    public static javax.swing.JLabel jLabelCorredor2Equipo7;
    public static javax.swing.JLabel jLabelCorredor2Equipo8;
    public static javax.swing.JLabel jLabelCorredor3Equipo1;
    public static javax.swing.JLabel jLabelCorredor3Equipo2;
    public static javax.swing.JLabel jLabelCorredor3Equipo3;
    public static javax.swing.JLabel jLabelCorredor3Equipo4;
    public static javax.swing.JLabel jLabelCorredor3Equipo5;
    public static javax.swing.JLabel jLabelCorredor3Equipo6;
    public static javax.swing.JLabel jLabelCorredor3Equipo7;
    public static javax.swing.JLabel jLabelCorredor3Equipo8;
    public static javax.swing.JLabel jLabelCorredor4Equipo1;
    public static javax.swing.JLabel jLabelCorredor4Equipo2;
    public static javax.swing.JLabel jLabelCorredor4Equipo3;
    public static javax.swing.JLabel jLabelCorredor4Equipo4;
    public static javax.swing.JLabel jLabelCorredor4Equipo5;
    public static javax.swing.JLabel jLabelCorredor4Equipo6;
    public static javax.swing.JLabel jLabelCorredor4Equipo7;
    public static javax.swing.JLabel jLabelCorredor4Equipo8;
    public static javax.swing.JLabel jLabelPista;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void start() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
